
privateKey=noaje3hw6rut
clientID=10008
#medHubUrl=https://ucsf-test.medhub.com
medHubUrl=https://ucsf.medhub.com

useIPMD=true
userIPMD=IPMD
userIPMDType=External
departmentPermission=138383
#apiUrl=https://dev-unified-api.ucsf.edu
apiUrl=https://unified-api.ucsf.edu
#authorization="Basic ZW1wJHVjc2ZkaXN0cmlidXQ6QDh4MkpnWXEmNjNWdEA="
#epicId="7c4ffb14-573a-47ba-9836-bf79e6837229"
evalInit=/functions/api/evals/initiate
evalForm=/functions/api/evals/forms
evalIncomplete=/functions/api/evals/incomplete
evalFacultySearch=/functions/api/users/facultySearch
evalResidentSearch=/functions/api/users/residentSearch
evalStatus=/functions/api/evals/status
scheduleService=/functions/api/schedules/services

dbApiUrl=https://dombonext.ucsf.edu
dbApiKey=3|6j42zBK9rHoCHlZzQw78xqKw4xybp1hVgWUrpbQh

#voalteHost=10.72.27.215
#voalteUser=svc_cw_voalte
#voaltePassword=SBX9v4L3u43F

#production
voalteHost=10.72.27.41
voalteUser=svc_cw_voalte
voaltePassword=v4L3u43FPR55


#stream section 
streamEpicClientID=f0f1f1af-0ed9-42e6-8c9d-1230e718fb27
tokenUrl=https://dev-unified-api.ucsf.edu/clinical/apex/oauth2/token
tokenUrlHost=dev-unified-api.ucsf.edu



#voalteFamilyHost=10.0.0.38
#voalteFamilyUser=postgres
#voalteFamilyPassword=123456a@


voalteFamilyHost=172.16.0.86
voalteFamilyUser=postgres
voalteFamilyPassword=postgres123


aws=172.16.0.86
awsUser=postgres
awsPassword=postgres123


dbHost=192.168.50.232
dbUser=postgres
dbPassword=postgres123
dbName=schedule


voalteDB002Host=172.16.0.86
voalteDB002User=postgres
voalteDB002Password=postgres123
voalteDB002UserCC=postgres
voalteDB002PasswordCC=postgres123
voalteDB002Database=cyberraptorPro


#authorization = "Basic ZW1wJHVjc2ZkaXN0cmlidXQ6WGZtR0hHZ043Y3ZzOUM="
#epicId = "93fa3ce5-03d9-446b-b715-046d8efbfa90"
authorization=Basic ZW1wJHVjc2ZkaXN0cmlidXQ6QDh4MkpnWXEmNjNWdEA=
epicId=7c4ffb14-573a-47ba-9836-bf79e6837229

enableOneLiner=true
checkPermission=true

userId=020444253
userIdType=UCSFEMPID

turnOnDebug=true


ucsfApiKey=MDE4YTFhMjg1ZTg3NGQ3Yzg5NDY5ZWE1OWNkMGRlYzM6NzE2N0RmMTliNTFBNDQwYzg0MThGMGUwRjc5YjY1NUM=
#ucsfApiKey=ccc59d0cae8f486cb1db71b4e4bb81b816bc9557b35fce4f8db8589e1a2fd029
ucsfApiUrl=https://unified-api.ucsf.edu/general/openai/deployments/gpt-4o-2024-08-06/chat/completions?api-version=2024-06-01
ucsfEmbeddingUrl=https://unified-api.ucsf.edu/general/openai/deployments/text-embedding-ada-002/embeddings?api-version=2024-06-01
#ucsfApiUrl=https://applet.ucsf.edu/backend/tools/proxy/chat
#ucsfEmbeddingUrl=https://applet.ucsf.edu/backend/tools/proxy/embedding
chromaUrl=http://chromadb:8000
chromaToken=ZCxWPqxpED1ivkP3twqTOVwo7JPX9qqoeP1UDF0VSzKQKKRy8EsDzZ7QTEVwtpQT   





